### ISSUE TITLE
.travis.yml is wrong

### ISSUE THREAD

**Issue by BanzaiMan** [bem-incubator/bem-social#26]
https://github.com/voischev/bem-social/blob/e690659f1d6cd0c8bb472a47fd7893f386394ab7/.travis.yml has:

``` yaml
matrix:
  - TEST_SCOPE: lint
  - TEST_SCOPE: tmpls
  - TEST_SCOPE: specs
  - TEST_SCOPE: gemini
```

Which I believe is meant to create a 4-job build matrix. But this is wrong. You need `matrix.include` instead, like so:

``` yaml
matrix:
  include:
    - TEST_SCOPE: lint
    - TEST_SCOPE: tmpls
    - TEST_SCOPE: specs
    - TEST_SCOPE: gemini
```

You can also use http://lint.travis-ci.org/voischev/bem-social to check your configuration.
